Repository mesh-adaptation/opt_adapt, pull requests merged in 2025-01, with the labels that each got.

#35 Make dev dependencies optional
  .github/workflows/test_suite.yml
  Makefile
  pyproject.toml
Labels: install

#36 Fix turbine solver
  demos/opt_uniform.py
  demos/turbine/Makefile
  demos/turbine/setup.py
Labels: bug, enhancement

#38 Fix gradient in turbine example
  demos/opt_go.py
  demos/opt_hessian.py
  demos/turbine/Makefile
  demos/turbine/plot_qoi.py
  demos/turbine/plot_results.py
  demos/turbine/setup.py
  opt_adapt/opt.py
Labels: bug
